using System.Text.Json.Serialization;

namespace WhatTheCoins.API.DTO.CoinGecko;

internal record TotalVolume(
    [property: JsonPropertyName("aed")] long? Aed,
    [property: JsonPropertyName("ars")] long? Ars,
    [property: JsonPropertyName("aud")] long? Aud,
    [property: JsonPropertyName("bch")] long? Bch,
    [property: JsonPropertyName("bdt")] long? Bdt,
    [property: JsonPropertyName("bhd")] long? Bhd,
    [property: JsonPropertyName("bmd")] long? Bmd,
    [property: JsonPropertyName("bnb")] long? Bnb,
    [property: JsonPropertyName("brl")] long? Brl,
    [property: JsonPropertyName("btc")] long? Btc,
    [property: JsonPropertyName("cad")] long? Cad,
    [property: JsonPropertyName("chf")] long? Chf,
    [property: JsonPropertyName("clp")] long? Clp,
    [property: JsonPropertyName("cny")] long? Cny,
    [property: JsonPropertyName("czk")] long? Czk,
    [property: JsonPropertyName("dkk")] long? Dkk,
    [property: JsonPropertyName("dot")] long? Dot,
    [property: JsonPropertyName("eos")] long? Eos,
    [property: JsonPropertyName("eth")] long? Eth,
    [property: JsonPropertyName("eur")] long? Eur,
    [property: JsonPropertyName("gbp")] long? Gbp,
    [property: JsonPropertyName("gel")] long? Gel,
    [property: JsonPropertyName("hkd")] long? Hkd,
    [property: JsonPropertyName("huf")] long? Huf,
    [property: JsonPropertyName("idr")] long? Idr,
    [property: JsonPropertyName("ils")] long? Ils,
    [property: JsonPropertyName("inr")] long? Inr,
    [property: JsonPropertyName("jpy")] long? Jpy,
    [property: JsonPropertyName("krw")] long? Krw,
    [property: JsonPropertyName("kwd")] long? Kwd,
    [property: JsonPropertyName("lkr")] long? Lkr,
    [property: JsonPropertyName("ltc")] long? Ltc,
    [property: JsonPropertyName("mmk")] long? Mmk,
    [property: JsonPropertyName("mxn")] long? Mxn,
    [property: JsonPropertyName("myr")] long? Myr,
    [property: JsonPropertyName("ngn")] long? Ngn,
    [property: JsonPropertyName("nok")] long? Nok,
    [property: JsonPropertyName("nzd")] long? Nzd,
    [property: JsonPropertyName("php")] long? Php,
    [property: JsonPropertyName("pkr")] long? Pkr,
    [property: JsonPropertyName("pln")] long? Pln,
    [property: JsonPropertyName("rub")] long? Rub,
    [property: JsonPropertyName("sar")] long? Sar,
    [property: JsonPropertyName("sek")] long? Sek,
    [property: JsonPropertyName("sgd")] long? Sgd,
    [property: JsonPropertyName("thb")] long? Thb,
    [property: JsonPropertyName("try")] long? Try,
    [property: JsonPropertyName("twd")] long? Twd,
    [property: JsonPropertyName("uah")] long? Uah,
    [property: JsonPropertyName("usd")] long? Usd,
    [property: JsonPropertyName("vef")] long? Vef,
    [property: JsonPropertyName("vnd")] long? Vnd,
    [property: JsonPropertyName("xag")] long? Xag,
    [property: JsonPropertyName("xau")] long? Xau,
    [property: JsonPropertyName("xdr")] long? Xdr,
    [property: JsonPropertyName("xlm")] long? Xlm,
    [property: JsonPropertyName("xrp")] long? Xrp,
    [property: JsonPropertyName("yfi")] long? Yfi,
    [property: JsonPropertyName("zar")] long? Zar,
    [property: JsonPropertyName("bits")] long? Bits,
    [property: JsonPropertyName("link")] long? Link,
    [property: JsonPropertyName("sats")] long? Sats
);